name: WyvernManagement

services:
  frontend:
    container_name: frontend
    image: wyvern-frontend-image
    build: 
      context: ./Frontend
      dockerfile: Dockerfile.dev
    volumes:
      - "./Frontend:/app"
    ports:
      - "5173:5173"
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/  
      && npm run dev"
  backend:
    container_name: backend
    image: wyvern-backend-image
    build: 
      context: ./Backend
      dockerfile: Dockerfile.dev
    volumes:
      - "./Backend:/app"
    ports:
      - "3000:3000"
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/  
      && npm run dev"
